### ISSUE TITLE
gminer confuses the gpus...

### ISSUE THREAD

**Issue by Tux0Topo** [cryptopoo/hiveos_gddr6x_temps#20] opened 2022-03-29 17:04 UTC
Hi there!
I´m using gminer v2.90, with 2x RTX 3030.
In the same ir is also lolminer runing some RX 5700XT (not sure if related).
The gui shows me no memory temps on the 2nd gpu, and the first gpu shows the temp of the 2nd.
On the miner log, everything is correct.
When tried lolminer or trex with the RTX everything worked fine...

**Comment by Tux0Topo** [comment] 2022-03-29 17:52
Forgot to specify that the tried unstable and stable versions....

**Comment by dedizones** [comment] 2022-03-29 19:15
You use hiveos ?

try restart service

Rig name ==> "Run Command" and paste this in console 

`systemctl restart gddr6x_temps.service`

**Comment by cryptopoo** [comment] 2022-03-29 19:53
Hello @Tux0Topo,

that's an interesting setup. I will do some research and I will see if I can come up to a solution.

Meanwhile, can you please run this command so I know a bit better about your setup?

```
gpu-stats
```

Please copy/paste what you get with it, thanks!

**Comment by Tux0Topo** [comment] 2022-03-29 20:13
The restart command, didn't fix anything.

The gpu-stats gave me these:

{"temp":["52","53","55","55","64","55","55","56"],"fan":["93","95","100","100","100","100","95","95"],"power":["122","229","125","127","116","137","219","71"],"busids":["07:00.0","08:00.0","0b:00.0","11:00.0","1
4:00.0","17:00.0","18:00.0","1c:00.0"],"brand":["amd","nvidia","amd","amd","amd","amd","nvidia","nvidia"],"load":["99","100","99","99","99","99","100","100"],"mtemp":["76","0","88","92","86","88","0","0"],"jtemp
":["64","0","64","81","72","63","0","0"]}

Also, these are the cards in the RIG:
As
 0 07:00.0 Radeon RX 5700 XT 8176 MB (115-D182PI0-101)       52°C
70°C   93 %  120 W
 1 08:00.0 GeForce RTX 3080 10240 MB (94.02.42.00.D6)        53°C
96°C   95 %  229 W
 2 0b:00.0 Radeon RX 5700 XT 8176 MB (BITBY.RU-MODDED)       56°C
88°C  100 %  125 W
 3 11:00.0 Radeon RX 5700 XT 8176 MB (115-D199PI0-101)       55°C
92°C  100 %  127 W
 4 14:00.0 Radeon RX 5700 XT 8176 MB (115-D199PI0-101)       64°C
86°C  100 %  115 W
 5 17:00.0 Radeon RX 5700 XT 8176 MB (115-D182PI0-100)       55°C
88°C  100 %  137 W
 6 18:00.0 GeForce RTX 3080 10240 MB (94.02.71.40.B1)        54°C
0°C   95 %  205 W
 7 1c:00.0 GeForce GTX 1650 SUPER 4096 MB (90.16.46.40.41)   56°C
0°C   95 %   70 W

Hope this helps!

**Comment by cryptopoo** [comment] 2022-03-29 22:06
Hi, now I have a good overview of your system, thanks.

When you reference the first and second GPU in your first message, do you mean the first and second NVIDIA GPU or the first (RX 5700 XT) and second (RTX 3080) ? Just wanted to be sure about this :)

**Comment by Tux0Topo** [comment] 2022-03-29 22:26
I was talking about both rtx 3080.
GPUS 1 and 6 on the list.
I attached a picture...
And i know, those temps are high...

**Comment by Tux0Topo** [comment] 2022-03-29 22:28
Another picture, but from the miner log

**Comment by cryptopoo** [comment] 2022-03-29 22:29
Can you please attach the pictures directly via github? They don't seem to be attached when answering via email :D

**Comment by cryptopoo** [comment] 2022-03-29 22:31
I modified the messages sent via email since they had your name in it ;)

**Comment by Tux0Topo** [comment] 2022-03-29 22:33
![20220329_192417](https://user-images.githubusercontent.com/20643337/160717706-9ce5649f-f904-463b-887d-f6cc2bb9df68.jpg)
![20220329_192750](https://user-images.githubusercontent.com/20643337/160717716-4c100513-3414-4623-8a74-9034b5f5aaab.jpg)

**Comment by cryptopoo** [comment] 2022-03-29 22:34
That's very clear now!

Can you please try again the unstable version now? That might fix this problem.

**Comment by Tux0Topo** [comment] 2022-03-29 22:43
Seems not fixed... rebooting the rig just in case...

**Comment by Tux0Topo** [comment] 2022-03-29 23:21
Nopes.... Not fixed...

**Comment by cryptopoo** [comment] 2022-03-30 00:11
While you have gminer and lolminer running, can you run this command and copy/paste the results?

```
curl -s "http://127.0.0.1:42010/stat" | json_pp; echo "====="; curl http://127.0.0.1:44444/summary | json_pp;
```

**Comment by cryptopoo** [comment] 2022-03-30 00:12
P.S. you may want to remove your address ("user") from the output

**Comment by Tux0Topo** [comment] 2022-03-30 00:27
{
   "speed_unit" : "H/s",
   "user2" : "user2",
   "total_stale_shares2" : 0,
   "speed_rate_precision2" : 0,
   "electricity" : 0.791,
   "shares_per_minute" : 2.38,
   "algorithm" : "Ethash + TON",
   "pool_speed" : 170266071,
   "total_invalid_shares" : 0,
   "total_stale_shares" : 0,
   "power_unit" : "H/W",
   "uptime" : 5601,
   "total_accepted_shares2" : 6,
   "shares_per_minute2" : 0.06,
   "power_unit2" : "H/W",
   "total_invalid_shares2" : 0,
   "miner" : "GMiner 2.90",
   "extended_share_info" : true,
   "user" : "user",
   "total_rejected_shares2" : 0,
   "pool_speed2" : 294512043,
   "server" : "eth.hiveon.com:4444",
   "total_accepted_shares" : 222,
   "server2" : "ssl://pool.services.tonwhales.com:443",
   "total_rejected_shares" : 0,
   "speed_rate_precision" : 0,
   "speed_unit2" : "H/s",
   "devices" : [
      {
         "bus_id" : "0000:08:00.0",
         "memory_temperature_limit" : 120,
         "fan" : 95,
         "invalid_shares2" : 0,
         "temperature_limit" : 90,
         "accepted_shares2" : 5,
         "memory_temperature" : 68,
         "temperature" : 51,
         "rejected_shares2" : 0,
         "stale_shares" : 0,
         "speed2" : 377246480,
         "power_usage" : 229,
         "rejected_shares" : 0,
         "invalid_shares" : 0,
         "memory_clock" : 10001,
         "name" : "3080",
         "speed" : 94311613,
         "stale_shares2" : 0,
         "gpu_id" : 0,
         "accepted_shares" : 123,
         "core_clock" : 1005
      },
      {
         "memory_clock" : 9851,
         "name" : "3080",
         "speed" : 68000003,
         "stale_shares2" : 0,
         "gpu_id" : 1,
         "core_clock" : 960,
         "accepted_shares" : 99,
         "temperature_limit" : 90,
         "memory_temperature" : 96,
         "accepted_shares2" : 1,
         "bus_id" : "0000:18:00.0",
         "memory_temperature_limit" : 120,
         "fan" : 95,
         "invalid_shares2" : 0,
         "power_usage" : 210,
         "rejected_shares" : 0,
         "invalid_shares" : 0,
         "rejected_shares2" : 0,
         "temperature" : 53,
         "stale_shares" : 0,
         "speed2" : 189760553
      },
      {
         "name" : "1650S",
         "speed" : 0,
         "memory_clock" : 6276,
         "stale_shares2" : 0,
         "gpu_id" : 2,
         "core_clock" : 1605,
         "accepted_shares" : 0,
         "memory_temperature_limit" : 120,
         "fan" : 95,
         "invalid_shares2" : 0,
         "bus_id" : "0000:1c:00.0",
         "temperature_limit" : 90,
         "accepted_shares2" : 0,
         "memory_temperature" : 0,
         "stale_shares" : 0,
         "speed2" : 0,
         "rejected_shares2" : 0,
         "temperature" : 54,
         "invalid_shares" : 0,
         "power_usage" : 70,
         "rejected_shares" : 0
      }
   ]
}
=====
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 127.0.0.1 port 44444: Connection refused
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/bin/json_pp line 45.

I´m running gminer on the RTX 3080, teamredminer on the 5700xt and custom lolminer on the gtx 1650s (better stability)

**Comment by cryptopoo** [comment] 2022-03-30 01:18
The problem is now clear to me.

I will have to fight a bit with gminer, but I should manage to fix it in the next 24hrs if I manage to find a little extra time for it.

Will keep you posted!

**Comment by Tux0Topo** [comment] 2022-03-30 01:30
Great! Thanks for your awesome work!

**Comment by cryptopoo** [comment] 2022-03-31 02:18
Hello @Tux0Topo!

If you could try the unstable version now, I bet you all the BTC I have (that's 0) that it will work, guaranteed ;)

**Comment by Tux0Topo** [comment] 2022-03-31 02:22
Trying it now cap!

**Comment by Tux0Topo** [comment] 2022-03-31 02:26
I´m glad to inform you that you keep all your BTC!!! IT WORKS!!!!
Awesome man!! Thank you!!!

**Comment by cryptopoo** [comment] 2022-03-31 02:29
Awesome! I'm waiting for all your BTCs then :D You have my address !

Closing this :) Cheers!

**Closed as completed by cryptopoo** 2022-03-31 02:29 UTC
